# Use the official Node.js image as the base image node 20 to use react router v7
FROM node:24-alpine3.21

# Set the working directory
WORKDIR /usr/src/app

COPY package*.json ./


COPY . .

EXPOSE 3000

CMD ["npm", "start"]